language: cpp
compiler: gcc
dist: precise

before_install:
 - pip install --user cpp-coveralls
script:
  - make && make coverage
after_success:
  - coveralls --exclude src/PyConv/test --exclude src/PyConv/main/util/logging/termcolor.hpp --gcov-options '\-lp'
